'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const crypto=require('node:crypto');
const {PersistentLifecycle}=require('../state/persistent-lifecycle');const {ZernioRouterAdapter,CAPABILITIES,createZernioTransport,sha256,proposalHash}=require('../core/zernio-router-adapter');
const tmp=()=>path.join(fs.mkdtempSync(path.join(os.tmpdir(),'alpha-zernio-ci-')),'lifecycle.log');
function make(extra={}){const p={proposalId:crypto.randomUUID(),content:'Alpha Sentinel launch',platforms:[{platform:'twitter',accountId:'acct-a'}],timezone:'UTC',expiresAt:new Date(1000000).toISOString(),...extra};p.proposalHash=proposalHash(p);return p;}
function setup(extra={}){const clock={value:0},lifecycle=new PersistentLifecycle(tmp(),{clock:()=>clock.value}),p=make(extra);lifecycle.createProposal(p);lifecycle.transition(p.proposalId,'HASHED');lifecycle.bindTransaction(p.proposalId,'tx');lifecycle.recordSimulation(p.proposalId,'tx',{success:true});lifecycle.startTimelock(p.proposalId,100);clock.value=100;lifecycle.recordSimulation(p.proposalId,'tx',{success:true,phase:'resimulation'});lifecycle.recordValidation(p.proposalId,p.proposalHash,{valid:true,validationHash:sha256({valid:true})});lifecycle.approve(p.proposalId,'approval-1');return{clock,lifecycle,p};}
function transport(){return{calls:[],async get(r,o){this.calls.push(['GET',r,o]);return r.startsWith('/posts/')?{post:{_id:r.split('/').pop(),status:'published'}}:{accounts:[]};},async post(r,o){this.calls.push(['POST',r,o]);if(r==='/tools/validate/post')return{valid:true};if(r==='/tools/validate/media')return{valid:true};return{post:{_id:'post-1',status:o.body?.scheduledFor?'scheduled':o.body?.publishNow?'published':'draft'}};}};}
const adapter=(s,t=transport(),secret='webhook-secret')=>new ZernioRouterAdapter({lifecycle:s.lifecycle,transport:t,webhookSecret:secret,clock:()=>s.clock.value});const sign=r=>crypto.createHmac('sha256','webhook-secret').update(r).digest('hex');

test('01 allowlist exactly v1',()=>assert.deepEqual(CAPABILITIES,['readAccounts','validatePost','validateMedia','createDraft','scheduleApproved','executeApproved','getExecutionStatus','ingestWebhook']));
test('02 readAccounts route',async()=>{const s=setup(),t=transport();await adapter(s,t).readAccounts({profileId:'p'});assert.equal(t.calls[0][1],'/accounts');});
test('03 validatePost evidence',async()=>{const s=setup();await adapter(s).validatePost(s.p);assert.equal(s.lifecycle.get(s.p.proposalId).validationValid,true);});
test('04 validateMedia route',async()=>{const s=setup(),t=transport();await adapter(s,t).validateMedia({url:'https://example.com/a.jpg'});assert.equal(t.calls[0][1],'/tools/validate/media');});
test('05 createDraft cannot publish',async()=>{const s=setup(),t=transport();await adapter(s,t).createDraft(s.p);assert.equal(t.calls[0][2].body.isDraft,true);assert.equal(t.calls[0][2].body.publishNow,undefined);});
test('06 LLM cannot publish directly',()=>{const a=adapter(setup());assert.equal(a.publishNow,undefined);assert.equal(a.post,undefined);assert.equal(Object.prototype.hasOwnProperty.call(a,'transport'),false);});
test('07 LLM cannot obtain credential',()=>{const s=setup(),key='sk_'+('a'.repeat(64)),tr=createZernioTransport({apiKey:key,fetchImpl:async()=>new Response('{}',{status:200})}),a=new ZernioRouterAdapter({lifecycle:s.lifecycle,transport:tr,webhookSecret:'webhook-secret'});assert.equal(Object.prototype.hasOwnProperty.call(a,'apiKey'),false);assert.equal(JSON.stringify(a).includes(key),false);});
test('08 unapproved proposal rejected',async()=>{const c={value:0},l=new PersistentLifecycle(tmp(),{clock:()=>c.value}),p=make();l.createProposal(p);await assert.rejects(new ZernioRouterAdapter({lifecycle:l,transport:transport(),webhookSecret:'webhook-secret',clock:()=>c.value}).executeApproved(p),/PROPOSAL_NOT_APPROVED/);});
test('09 modified proposal rejected',async()=>{const s=setup(),p={...s.p,content:'mutated'};p.proposalHash=proposalHash(p);await assert.rejects(adapter(s).executeApproved(p),/APPROVED_PROPOSAL_MISMATCH/);});
test('10 wrong account rejected',async()=>{const s=setup(),p={...s.p,platforms:[{platform:'twitter',accountId:'acct-b'}]};p.proposalHash=proposalHash(p);await assert.rejects(adapter(s).executeApproved(p),/APPROVED_PROPOSAL_MISMATCH/);});
test('11 wrong platform rejected',async()=>{const s=setup(),p={...s.p,platforms:[{platform:'linkedin',accountId:'acct-a'}]};p.proposalHash=proposalHash(p);await assert.rejects(adapter(s).executeApproved(p),/APPROVED_PROPOSAL_MISMATCH/);});
test('12 expired proposal rejected',async()=>{const s=setup();s.clock.value=1000000;await assert.rejects(adapter(s).executeApproved(s.p),/PROPOSAL_EXPIRED/);});
test('13 timelock cannot be bypassed',async()=>{const p=make(),l={get:()=>({proposal:p,state:'APPROVED',timelockUntil:200,approval:{proposalHash:p.proposalHash},validationValid:true,validationBindingHash:'v'})};await assert.rejects(new ZernioRouterAdapter({lifecycle:l,transport:transport(),webhookSecret:'webhook-secret',clock:()=>100}).executeApproved(p),/TIMELOCK_ACTIVE/);});
test('14 failed validation rejected',async()=>{const s=setup();s.lifecycle.recordValidation(s.p.proposalId,s.p.proposalHash,{valid:false,validationHash:sha256({valid:false})});await assert.rejects(adapter(s).executeApproved(s.p),/VALIDATION_REQUIRED/);});
test('15 scheduleApproved correlated',async()=>{const s=setup({scheduledFor:new Date(2000000).toISOString()});const r=await adapter(s).scheduleApproved(s.p);assert.equal(r.post.status,'scheduled');assert.equal(s.lifecycle.get(s.p.proposalId).externalExecution.mode,'schedule');});
test('16 executeApproved binds post',async()=>{const s=setup(),t=transport();await adapter(s,t).executeApproved(s.p);const c=t.calls.find(x=>x[1]==='/posts');assert.equal(c[2].body.publishNow,true);assert.match(c[2].requestId,/^[0-9a-f-]{36}$/);assert.equal(s.lifecycle.get(s.p.proposalId).externalExecution.postId,'post-1');});
test('17 getExecutionStatus reads status',async()=>{const s=setup(),t=transport();assert.equal((await adapter(s,t).getExecutionStatus('post-1')).post.status,'published');});
test('18 signed published webhook reaches VERIFIED',async()=>{const s=setup(),a=adapter(s);await a.executeApproved(s.p);const raw=JSON.stringify({id:'evt-1',event:'post.published',post:{id:'post-1'}});assert.equal(a.ingestWebhook({rawBody:raw,signature:sign(raw)}).state,'VERIFIED');});
test('19 duplicate webhook cannot duplicate transition',async()=>{const s=setup(),a=adapter(s);await a.executeApproved(s.p);const raw=JSON.stringify({id:'evt-dup',event:'post.published',post:{id:'post-1'}});a.ingestWebhook({rawBody:raw,signature:sign(raw)});const v=s.lifecycle.get(s.p.proposalId).version;assert.equal(a.ingestWebhook({rawBody:raw,signature:sign(raw)}).duplicate,true);assert.equal(s.lifecycle.get(s.p.proposalId).version,v);});
test('20 invalid signature cannot mutate state',async()=>{const s=setup(),a=adapter(s);await a.executeApproved(s.p);const before=s.lifecycle.get(s.p.proposalId);assert.throws(()=>a.ingestWebhook({rawBody:JSON.stringify({id:'bad',event:'post.published',post:{id:'post-1'}}),signature:'bad'}),/INVALID_WEBHOOK_SIGNATURE/);assert.deepEqual(s.lifecycle.get(s.p.proposalId),before);});
test('21 unknown post cannot mutate proposal',()=>{const s=setup(),a=adapter(s),raw=JSON.stringify({id:'evt-unknown',event:'post.published',post:{id:'attacker'}}),before=s.lifecycle.get(s.p.proposalId);assert.equal(a.ingestWebhook({rawBody:raw,signature:sign(raw)}).correlated,false);assert.deepEqual(s.lifecycle.get(s.p.proposalId),before);});
test('22 failed webhook rejects broadcast',async()=>{const s=setup(),a=adapter(s);await a.executeApproved(s.p);const raw=JSON.stringify({id:'evt-fail',event:'post.failed',post:{id:'post-1'}});assert.equal(a.ingestWebhook({rawBody:raw,signature:sign(raw)}).state,'REJECTED');});
test('23 platform event does not falsely verify',async()=>{const s=setup(),a=adapter(s);await a.executeApproved(s.p);const raw=JSON.stringify({id:'evt-platform',event:'post.platform.published',post:{id:'post-1'}});assert.equal(a.ingestWebhook({rawBody:raw,signature:sign(raw)}).state,'BROADCAST');});
test('24 external post correlation survives restart',async()=>{const s=setup(),a=adapter(s);await a.executeApproved(s.p);const l2=new PersistentLifecycle(s.lifecycle.filePath,{clock:()=>s.clock.value}),a2=new ZernioRouterAdapter({lifecycle:l2,transport:transport(),webhookSecret:'webhook-secret',clock:()=>s.clock.value}),raw=JSON.stringify({id:'evt-restart',event:'post.published',post:{id:'post-1'}});assert.equal(a2.ingestWebhook({rawBody:raw,signature:sign(raw)}).state,'VERIFIED');});
test('25 audit chain valid after reconciliation',async()=>{const s=setup(),a=adapter(s);await a.executeApproved(s.p);const raw=JSON.stringify({id:'evt-audit',event:'post.published',post:{id:'post-1'}});a.ingestWebhook({rawBody:raw,signature:sign(raw)});assert.equal(s.lifecycle.verifyAuditChain(),true);});
test('26 approval requires resimulation',()=>{const c={value:0},l=new PersistentLifecycle(tmp(),{clock:()=>c.value}),p=make();l.createProposal(p);l.transition(p.proposalId,'HASHED');l.bindTransaction(p.proposalId,'tx');l.recordSimulation(p.proposalId,'tx',{success:true});assert.throws(()=>l.approve(p.proposalId,'x'),/APPROVAL_REQUIRES_RESIMULATION/);});
test('27 resimulation cannot bypass timelock',()=>{const c={value:0},l=new PersistentLifecycle(tmp(),{clock:()=>c.value}),p=make();l.createProposal(p);l.transition(p.proposalId,'HASHED');l.bindTransaction(p.proposalId,'tx');l.recordSimulation(p.proposalId,'tx',{success:true});l.startTimelock(p.proposalId,100);assert.throws(()=>l.recordSimulation(p.proposalId,'tx',{success:true,phase:'resimulation'}),/TIMELOCK_ACTIVE/);});
test('28 transaction binding mismatch rejected',()=>{const s=setup();assert.throws(()=>s.lifecycle.recordSimulation(s.p.proposalId,'wrong',{success:true}),/TRANSACTION_BINDING_MISMATCH/);});
test('29 duplicate proposal rejected',()=>{const s=setup();assert.throws(()=>s.lifecycle.createProposal(s.p),/PROPOSAL_ALREADY_EXISTS/);});
test('30 invalid lifecycle transition rejected',()=>{const s=setup();assert.throws(()=>s.lifecycle.transition(s.p.proposalId,'VERIFIED'),/INVALID_TRANSITION/);});
test('31 stale version rejected',()=>{const s=setup(),r=s.lifecycle.get(s.p.proposalId);assert.throws(()=>s.lifecycle.transition(s.p.proposalId,'REJECTED',{},r.version-1),/VERSION_CONFLICT/);});
